sudo: required
dist: trusty

addons:
   chrome: stable

language: php

php:
    - 7.3

services:
    - memcached

notifications:
  email:
    - barryo@inex.ie

before_install:
    - sudo apt-get update
    - "./data/travis-ci/setup_tests.sh"

after_failure:
    - "./data/travis-ci/after_failure.sh"

